altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  fe3f6153-ca14-4237-9866-282daa4d6f5f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-05T16:49:02+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: d977615b-a195-4f6a-bfc9-c1a99096df3c
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 50f15354-2c40-4651-bd7c-7abc02733c63
        userCondition: null
fs: cloudflarer2
handle: cloudflarer2
name: cloudflareR2
sortOrder: 4
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
