altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  89f6441e-0a70-4c8a-bc31-8fcc64d3d0ea:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-05T16:49:36+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 1ba924f9-702e-46a2-a8cd-0c0794231df9
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 49496941-b5e5-415d-815a-c6841d0ca9fb
        userCondition: null
fs: commons3
handle: commons3
name: commonS3
sortOrder: 7
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
