altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  645caae2-bad7-4afa-ade5-679b8d6daecd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-05T16:49:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 496fc5a1-e01a-40c6-a104-38877a3d7591
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 72f7bf05-3bbf-48f6-87b0-5f0324cc33de
        userCondition: null
fs: customflysystem
handle: customflysystem
name: customFlysystem
sortOrder: 8
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
