altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  ac10a867-b11b-4cdc-9cb5-1bea62a13b5f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-05T16:49:17+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 743a8d5a-798d-4259-8041-ec8ba43d3429
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: b1ea6d6c-9400-41b0-b93f-4c5d843d3d5b
        userCondition: null
fs: digitalocean
handle: digitalocean
name: digitalOcean
sortOrder: 5
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
