altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  22f747dc-606a-4812-8582-d6c847d74b5a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-05T16:49:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 9d84ffa5-79d0-44ff-8a0a-292e58ab5383
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 4e6f8186-f9bd-49fc-89dc-264e96b2ee59
        userCondition: null
fs: googlecloudstorage
handle: googlecloudstorage
name: googleCloudStorage
sortOrder: 6
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
