altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  b8d8403b-eb60-4f90-9d24-85bf819b0af0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-12-18T12:04:04+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 0eb3277f-d8ff-4294-9799-1bfc7c4ed4a7
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 58fb3cee-74b8-4e1b-9e55-5613859d3412
        userCondition: null
fs: main
handle: main
name: Main
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
