altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  b56b2cfd-5c99-4e10-8af5-0d69caffcd41:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-01-04T16:39:33+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4bf0b3d0-efdf-4d81-90c5-a3df9c35dab7
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: b57accbe-b6f9-4cae-9530-b5be4b9e6d73
        userCondition: null
fs: videos
handle: videos
name: Videos
sortOrder: 2
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
